src/PiBundle/Entity/Evenement.php
<?php

namespace PiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Evenement
 *
 * @ORM\Table(name="evenement")
 * @ORM\Entity(repositoryClass="PiBundle\Repository\EvenementRepository")
 */
class Evenement
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     *
     * @Assert\Length(min=5,minMessage="Le nom doit avoir au minimum 5 lettres")
     * @Assert\Length(max=20,maxMessage="Le nom doit avoir au maximum 20 lettres")
     */
    private $nom;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_debut", type="datetime")
     *
     */
    private $dateDebut;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_fin", type="datetime")
     *
     */
    private $dateFin;

    /**
     * @var int
     *
     * @ORM\Column(name="disponibles", type="integer")
     *
     * @Assert\Range(min=10,minMessage="Les places disponibles doivent être supérieure à 10")
     * @Assert\Range(max=1000,maxMessage="Les places diponibles doivent être inférieure à 1000")
     */
    private $disponibles;

    /**
     * @var float
     *
     * @ORM\Column(name="cout_reservation", type="float")
     */
    private $coutReservation;

    /**
     * @var string
     *
     * @ORM\Column(name="age", type="string", length=255)
     */
    private $age;


    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;

    /**
     * @return string
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * @param string $age
     */
    public function setAge($age)
    {
        $this->age = $age;
    }

    /**
     * @var float
     *
     * @ORM\Column(name="prix", type="float")
     *
     * @Assert\Range(min=0,minMessage="Le prix doit être supérieure à 0DT")
     * @Assert\Range(max=100,maxMessage="Le prix doit être inférieure à 100DT")
     */
    private $prix;

    /**
     * @var float
     *
     * @ORM\Column(name="prix_etudiants", type="float")
     *
     * @Assert\Range(min=0,minMessage="Le prix pour les étudiants doit être supérieure à 0DT")
     * @Assert\Range(max=100,maxMessage="Le prix pour les étudiants doit être inférieure à 100DT")
     */
    private $prixEtudiants;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255)
     *
     * @Assert\Length(min=10,minMessage="La description doit avoir au minimum 10 lettres")
     * @Assert\Length(max=255,maxMessage="la description doit avoir au maximum 255 lettres")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="etat", type="string", length=255)
     */
    private $etat;


    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @var string
     *
     * @ORM\Column(name="image_id", type="string", length=255)
     */


    private $Img;

    /**
     * @return mixed
     */
    public function getImg()
    {
        return $this->Img;
    }

    /**
     * @param mixed $Img
     */
    public function setImg($Img)
    {
        $this->Img = $Img;
    }

    /**
     * @ORM\ManyToOne(targetEntity="Salle", inversedBy="Evenement")
     * @ORM\JoinColumn(name="salle_id", referencedColumnName="id")
     */


    private $Salle;

    /**
     * @return mixed
     */
    public function getSalle()
    {
        return $this->Salle;
    }

    /**
     * @param mixed $Salle
     */
    public function setSalle($Salle)
    {
        $this->Salle = $Salle;
    }
    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Evenement
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set dateDebut
     *
     * @param \DateTime $dateDebut
     *
     * @return Evenement
     */
    public function setDateDebut($dateDebut)
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    /**
     * Get dateDebut
     *
     * @return \DateTime
     */
    public function getDateDebut()
    {
        return $this->dateDebut;
    }

    /**
     * Set dateFin
     *
     * @param \DateTime $dateFin
     *
     * @return Evenement
     */
    public function setDateFin($dateFin)
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    /**
     * Get dateFin
     *
     * @return \DateTime
     */
    public function getDateFin()
    {
        return $this->dateFin;
    }

    /**
     * Set disponibles
     *
     * @param integer $disponibles
     *
     * @return Evenement
     */
    public function setDisponibles($disponibles)
    {
        $this->disponibles = $disponibles;

        return $this;
    }

    /**
     * Get disponibles
     *
     * @return int
     */
    public function getDisponibles()
    {
        return $this->disponibles;
    }

    /**
     * Set coutReservation
     *
     * @param float $coutReservation
     *
     * @return Evenement
     */
    public function setCoutReservation($coutReservation)
    {
        $this->coutReservation = $coutReservation;

        return $this;
    }

    /**
     * Get coutReservation
     *
     * @return float
     */
    public function getCoutReservation()
    {
        return $this->coutReservation;
    }



    /**
     * Set prix
     *
     * @param float $prix
     *
     * @return Evenement
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * Get prix
     *
     * @return float
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * Set prixEtudiants
     *
     * @param float $prixEtudiants
     *
     * @return Evenement
     */
    public function setPrixEtudiants($prixEtudiants)
    {
        $this->prixEtudiants = $prixEtudiants;

        return $this;
    }

    /**
     * Get prixEtudiants
     *
     * @return float
     */
    public function getPrixEtudiants()
    {
        return $this->prixEtudiants;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Evenement
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set etat
     *
     * @param string $etat
     *
     * @return Evenement
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * Get etat
     *
     * @return string
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @Assert\Callback
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if ($this->getPrixEtudiants()>$this->getPrix()) {
            $context->buildViolation('Le prix pour les étudiants doit être inférieure au prix')
                ->atPath('prixEtudiants')
                ->addViolation();
        }
        if ($this->getDateDebut()>$this->getDateFin()) {
            $context->buildViolation('La date fin doit être supérieure à la date début')
                ->atPath('date_fin')
                ->addViolation();
        }
        date_default_timezone_set('Africa/Tunis');
        $date = new \DateTime();
        if ($this->getDateDebut()<$date && empty($this->getId())) {
            $context->buildViolation('La date début doit être supérieure à la date actuelle')
                ->atPath('date_debut')
                ->addViolation();
        }
    }

    public function __toString()
    {
        return $this->getId().' '.$this->getNom();
    }


}

src/PiBundle/Form/EvenementForm.php
<?php
/**
 * Created by PhpStorm.
 * User: missaoui
 * Date: 22/03/2019
 * Time: 15:29
 */

namespace PiBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\DateTime;

class EvenementForm extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add("nom",TextType::class,array('attr' => array(
            'placeholder' => 'Entrer nom',
        )))
            ->add("age", ChoiceType::class, [
                'choices'  => [
                    'Interdit au moins de 12 ans' => 'interdit_12_ans',
                    'Tout public' => 'tout_public',
                    'Pour enfants' => 'pour_enfants',
                ],
                'placeholder'=>'Sélectionner un age',
            ])
            ->add('prix',IntegerType::class)
            ->add('prixEtudiants',IntegerType::class)
            ->add("description",TextAreaType::class,array('attr' => array(
                'placeholder' => 'Entrer description'
            )))
            ->add("Img",FileType::class,array('label'=>'Image','data_class' => null,'required'=>false));
        $builder->add("date_debut", DateTimeType::class,array(
            'widget' => 'single_text',
            'input' => 'datetime',
        ));
        $builder->add("date_fin", DateTimeType::class,array(
            'widget' => 'single_text',
            'input' => 'datetime',
        ));
        $builder->add('disponibles',IntegerType::class);
        $builder->add("type", ChoiceType::class, [
            'choices'  => [
                'Sélectionner un type' =>'',
                'film' => 'film',
                'theatre' => 'theatre',
                'formation' => 'formation',
                'festival' => 'festival',
                'musique' => 'musique',
                'expose' => 'expose',
            ],
        ]);
        $builder->add('Salle', EntityType::class, array(
            'required' => true,
            'placeholder' => "Insérer les valeurs nécessaires d'abord",
            'class' => 'PiBundle:Salle',
            'choice_label'=>'nom',
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'PiBundle\Entity\Evenement'
        ));
    }

    public function getName()
    {
        return 'pi_bundle_evenement_form';
    }

    public function getBlockPrefix()
    {
        return 'pi_bundle_evenement_form';
    }
}

src/PiBundle/Resources/views/Evenement/afficher.html.twig
{% extends 'front.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
    <div class="d-lg-flex position-relative">
        <div class="container d-lg-flex align-items-lg-center space-top-2 space-top-md-5 space-lg-0 min-height-lg-100vh">
            <!-- Content -->

            <div>
                <br><br><br><br><br><br><br>
                <h2>Afficher Les Evènements</h2>
                <div class="form-group form-inline">
                    <label for="recherche" class="col-md-3">Recherche</label>
                    <input type="text" class="form-control col-md-7" onkeyup="rechercher()" id="recherche">
                </div>
                <br>
                <div class="card-sm-columns" style="width: 800px;">
                {% for e in events %}
                        <div class="card text-center border-dark mb-11" style="width: 21rem; margin-left: 20px; margin-right: 20px;
                        {% if(e.type=='film') %} background-color : #3F51B5;
                        {% elseif(e.type=='theatre') %} background-color : #7986CB;
                        {% elseif(e.type=='formation') %} background-color : #303F9F;
                        {% elseif(e.type=='festival') %} background-color : #536DFE;
                        {% elseif(e.type=='musique') %} background-color : #304FFE;
                        {% elseif(e.type=='expose') %} background-color : #5C6BC0;
                        {% endif %} ">
                            <div class="card-img-top" style="position: relative; height: 200px">
                                <a href="afficherEvenement/{{ e.id }}"><img src="{{ asset("getImage.php?file="~e.img) }}" alt="{{ e.img }}" style="width: 100%; height :100%;"></a>
                                <div style="position: absolute; opacity: 0.95; height: 100%; width: 35%;  bottom: 0;  right: 0; text-align: center;  padding-left: 10px;  padding-right: 10px; {% if(e.type=='film') %} background-color : #3F51B5;
                                {% elseif(e.type=='theatre') %} background-color : #7986CB;
                                {% elseif(e.type=='formation') %} background-color : #303F9F;
                                {% elseif(e.type=='festival') %} background-color : #536DFE;
                                {% elseif(e.type=='musique') %} background-color : #304FFE;
                                {% elseif(e.type=='expose') %} background-color : #5C6BC0;
                                {% endif %} ">
                                    <p style="color: white; font-size: 17px; padding-top: 30px;padding-bottom: 0">PRIX : {{ e.prix }} DT</p>
                                    <i class="fa fa-ticket fa-3x" style="color: white;"></i>
                                    <p style="color: white; font-size: 11px; padding-top: 10px;">(PRIX POUR LES ETUDIANTS : {{ e.prixEtudiants }} DT)</p>
                                </div>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title" style="color: white">{{ e.type }} : {{ e.nom }}</h5>
                                <h6 class="card-subtitle mb-2" style="color: black">{{ e.salle.nom }}</h6>
                                <div class="card-text" style="color: navajowhite; height: 55px; overflow: hidden; text-overflow:ellipsis; font-size: 12px">{{ e.description }}</div>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item-warning" style="text-align : left; color: black">&nbsp;<i class="fa fa-clock"></i>&nbsp; Debut : {{ e.dateDebut|date }}</li>
                                <li class="list-group-item-warning" style="text-align : left; color: black">&nbsp;<i class="fa fa-clock" style="color: grey"></i>&nbsp; Fin : {{ e.dateFin|date }}</li>
                            </ul>
                            {% if app.user is not null and date(e.dateDebut) > date("now") %}
                            <div class="card-body">
                                <a href="#aaaa" class="btn btn-indigo"><i class="fa fa-shopping-cart"></i> Participer</a>
                            </div>
                            {% elseif app.user is not null %}
                                <div class="card-body">
                                    <button disabled="disabled" href="#aaaa" class="btn btn-indigo"><i class="fa fa-shopping-cart"></i> Participer</button>
                                </div>
                            {% endif %}
                        </div>
                {% endfor %}
                </div>
            </div>
            <div style="width: 400px">
                <h4>Recommandations</h4>
                {% if rec|length > 0 %}
                    <a href="{{ path('recommander') }}">Afficher tout</a>
                {% for r in rec %}
                <a href="{{ path('afficherEvenement', {'id': r.id}) }}">
                    <div class="card text-white bg-secondary mb-3" style="width: 16rem; height: 10rem; padding: 5px;">
                        <img class="card-img-top" style="opacity: 0.5; height: 100%; height: 100%;" src="{{ asset("getImage.php?file="~r.img) }}" alt="Card image">
                        <div class="card-img-overlay text-center">
                            <h4 class="card-title">{{ r.nom }}</h4>
                        </div>
                    </div>
                </a>
                {% endfor %}
                {% elseif app.user is null %}
                    <p>Vous devez être connecté pour voir les recommendations</p>
                {% else %}
                    <a href="{{ path('recommander') }}">Afficher tout</a>
                    <p>Vous n'avez pas des recommendations</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script>
    function rechercher()
    {
        $.ajax({
            url: "{{ path('evenement_list_arechercher') }}",
            type: "GET",
            dataType: "JSON",
            data: {
                rech: $("#recherche").val()
            },
            success: function (evenements) {
                var cardColmuns = $(".card-sm-columns");

                cardColmuns.html('');

                $.each(evenements, function (key, ev) {
                    var bg = "#3F51B5";
                    if (ev.type === 'film') {
                        bg = "#3F51B5;";
                    }
                    if (ev.type === 'theatre') {
                        bg = "#7986CB;";
                    }
                    if (ev.type === 'festival') {
                        bg = "#536DFE;";
                    }
                    if (ev.type === 'formation') {
                        bg = "#303F9F;";
                    }
                    if (ev.type === 'expose') {
                        bg = "#5C6BC0;";
                    }
                    if (ev.type === 'musique') {
                        bg = "#304FFE;";
                    }
                    var bool = "";
                    if(Date.parse(ev.dateDebut) < Date.now())
                    {
                        bool = "disabled";
                    }
                    cardColmuns.append('<div class="card text-center border-dark mb-11" style="width: 21rem; margin-left: 20px; margin-right: 20px; display: inline-block;\n' +
                        ' background-color : ' + bg + '"><div class="card-img-top" style="position: relative; height: 200px">\n' +
                        '<a href="http://localhost/PiDev/web/app_dev.php/evenement/afficherEvenement/' + ev.id + '"><img src="http://localhost/PiDev/web/getImage.php?file=' + ev.img + '" alt="' + ev.img + '" style="width: 100%; height :100%;"></a>\n' +
                        '<div style="position: absolute; opacity: 0.95; height: 100%; width: 35%;  bottom: 0;  right: 0; text-align: center;  padding-left: 10px;  padding-right: 10px; ' +
                        ' background-color : ' + bg + '">\n' +
                        '                                    <p style="color: white; font-size: 17px; padding-top: 30px;padding-bottom: 0">PRIX : ' + ev.prix + ' DT</p>\n' +
                        '                                    <i class="fa fa-ticket fa-3x" style="color: white;"></i>\n' +
                        '                                    <p style="color: white; font-size: 11px; padding-top: 10px;">(PRIX POUR LES ETUDIANTS : ' + ev.prixEtudiants + ' DT)</p>\n' +
                        '                                </div>\n' +
                        '                            </div>\n' +
                        '                            <div class="card-body">\n' +
                        '                                <h5 class="card-title" style="color: white">' + ev.type + ' : ' + ev.nom + '</h5>\n' +
                        '                                <h6 class="card-subtitle mb-2" style="color: black">' + ev.salle + '</h6>\n' +
                        '                                <div class="card-text" style="color: navajowhite; height: 55px; overflow: hidden; text-overflow:ellipsis; font-size: 12px">' + ev.description + '</div>\n' +
                        '                            </div>\n' +
                        '                            <ul class="list-group list-group-flush">\n' +
                        '                                <li class="list-group-item-warning" style="text-align : left; color: black">&nbsp;<i class="fa fa-clock"></i>&nbsp; Debut : ' + ev.dateDebut + '</li>\n' +
                        '                                <li class="list-group-item-warning" style="text-align : left; color: black">&nbsp;<i class="fa fa-clock" style="color: grey"></i>&nbsp; Fin : ' + ev.dateFin + '</li>\n' +
                        '                            </ul>\n' +
                                    {% if app.user is not null %}
                        '                            <div class="card-body">\n' +
                        '                                <button href="#aaaa" '+bool+' class="btn btn-indigo"><i class="fa fa-shopping-cart"></i> Participer</button>\n' +
                        '                            </div>\n' +
                                    {% endif %}
                        '                        </div>');

                });
            },
            error: function (err) {

            }
        });
    }
</script>
{% endblock %}

src/PiBundle/Resources/views/Evenement/afficherOrganisateur.html.twig
{% extends 'front.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
    <div class="d-lg-flex position-relative">
        <div class="container d-lg-flex align-items-lg-center space-top-2 space-top-md-5 space-lg-0 min-height-lg-auto">
            <!-- Content -->

            <div>
                <br><br><br><br><br><br><br>
                <h2>Afficher Mes Evènements &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{{ path('ajouter') }}"><i class="fa fa-plus-square fa-2x"></i></a>
                    <a href="{{ path('mesStats') }}"><i class="fa fa-chart-area fa-2x"></i></a></h2>
                <br>
                <div class="card-sm-columns" style="width: 1200px;">
                    {% for e in events %}
                        <div class="card text-center border-dark mb-11" style="width: 21rem; margin-left: 20px; margin-right: 20px;
                        {% if(e.type=='film') %} background-color : #3F51B5;
                        {% elseif(e.type=='theatre') %} background-color : #7986CB;
                        {% elseif(e.type=='formation') %} background-color : #303F9F;
                        {% elseif(e.type=='festival') %} background-color : #536DFE;
                        {% elseif(e.type=='musique') %} background-color : #304FFE;
                        {% elseif(e.type=='expose') %} background-color : #5C6BC0;
                        {% endif %} ">
                            <div class="card-header">
                                {{ e.etat|replace('_',' ')|upper }}
                            </div>
                            <div class="card-img-top" style="position: relative; height: 200px">
                                <a href="afficherEvenement/{{ e.id }}"><img src="{{ asset("getImage.php?file="~e.img) }}" alt="{{ e.img }}" style="width: 100%; height :100%;"></a>
                                <div style="position: absolute; opacity: 0.95; height: 100%; width: 35%;  bottom: 0;  right: 0; text-align: center;  padding-left: 10px;  padding-right: 10px; {% if(e.type=='film') %} background-color : #3F51B5;
                                {% elseif(e.type=='theatre') %} background-color : #7986CB;
                                {% elseif(e.type=='formation') %} background-color : #303F9F;
                                {% elseif(e.type=='festival') %} background-color : #536DFE;
                                {% elseif(e.type=='musique') %} background-color : #304FFE;
                                {% elseif(e.type=='expose') %} background-color : #5C6BC0;
                                {% endif %} ">
                                    <p style="color: white; font-size: 17px; padding-top: 30px;padding-bottom: 0">PRIX : {{ e.prix }} DT</p>
                                    <i class="fa fa-ticket fa-3x" style="color: white;"></i>
                                    <p style="color: white; font-size: 11px; padding-top: 10px;">(PRIX POUR LES ETUDIANTS : {{ e.prixEtudiants }} DT)</p>
                                </div>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title" style="color: white">{{ e.type }} : {{ e.nom }}</h5>
                                <h6 class="card-subtitle mb-2" style="color: black">{{ e.salle.nom }}</h6>
                                <div class="card-text" style="color: navajowhite; height: 55px; width: 100%; overflow: hidden; text-overflow:ellipsis; font-size: 12px">{{ e.description }}</div>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item-warning" style="text-align : left; color: black">&nbsp;<i class="fa fa-clock"></i>&nbsp; Debut : {{ e.dateDebut|date }}</li>
                                <li class="list-group-item-warning" style="text-align : left; color: black">&nbsp;<i class="fa fa-clock" style="color: grey"></i>&nbsp; Fin : {{ e.dateFin|date }}</li>
                            </ul>
                            <div class="card-body">
                                <a href="{{ path('modifierEvenement',{'id':e.id}) }}" class="btn btn-warning"><i class="fa fa-edit"></i> Modifier</a>
                                <a href="{{ path('supprimerEvenement',{'id':e.id}) }}" class="btn btn-danger"><i class="fa fa-eraser"></i> Supprimer</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/PiBundle/Resources/views/Evenement/mesStats.html.twig
{% extends 'front.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/starrating/css/rating.css') }}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="{{ asset('bundles/starrating/js/rating.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="d-lg-flex position-relative">
        <div class="container d-lg-flex align-items-lg-center space-top-2 space-top-md-5 space-lg-0 min-height-lg-auto">
            <!-- Content -->

            <div>
                <br><br><br><br><br>
                <h2>Mes Statistiques</h2>
                <p style="padding-left: 20px; color: darkslateblue;">Vous avez crée {{ nbr }} évènements qui sont répartis comme suit:</p>
                <div style="display: inline-flex; width: 1200px;">
                    <div id="div_pie2"></div>
                    <div id="div_pie"></div>
                </div>
                <p style="padding-left: 20px; color: darkslateblue;">L'évènement avec la meilleure note moyenne est <a href="{{ path('afficherEvenement', {'id': evmax.id}) }}">{{ evmax.nom }}</a> avec {{ evmaxmoy }}.</p>
                <p style="padding-left: 20px; color: darkslateblue;">L'évènement avec la meilleure note moyenne est <a href="{{ path('afficherEvenement', {'id': evmin.id}) }}">{{ evmin.nom }}</a> avec {{ evminmoy }}.</p>
                <div id="div_histogram"></div>
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                <script type="text/javascript">
                    {{ gc_draw([histogram,pieChart,pieChart2], ['div_histogram','div_pie','div_pie2']) }}
                </script>
            </div>
        </div>
    </div>
{% endblock %}